---
- name: Check if k3s_linux-amd64 exitst
  local_action: stat path="{{ inventory_dir }}/dynamic_vars/files/download/k3s/{{ k3s.version }}/k3s"
  run_once: true
  become: no
  register: file_adm64

- name: Check if k3s_linux-arm64 exitst
  local_action: stat path="{{ inventory_dir }}/dynamic_vars/files/download/k3s/{{ k3s.version }}/k3s-arm64"
  run_once: true
  become: no
  register: file_arm64

- name: Check if k3s_linux-arm exitst
  local_action: stat path="{{ inventory_dir }}/dynamic_vars/files/download/k3s/{{ k3s.version }}/k3s_armfh"
  run_once: true
  become: no
  register: file_arm

- name: Downloading newest k3s binaries locally
  local_action: get_url url="{{ item }}" dest="{{ inventory_dir }}/dynamic_vars/files/download/k3s/{{ k3s.version }}"
  run_once: true
  become: no
  with_items: 
    - https://github.com/rancher/k3s/releases/download/{{ k3s.version }}/k3s
    - https://github.com/rancher/k3s/releases/download/{{ k3s.version }}/k3s-arm64
    - https://github.com/rancher/k3s/releases/download/{{ k3s.version }}/k3s-armhf
  when:
    - (not file_adm64.stat.exists) or (not file_arm64.stat.exists) or (not file_arm.stat.exists)