---
- name: Cleanup k3s
  include_tasks: k3s-cleanup.yml
  tags: [ never, cleanup ]

- name: Cleanup other kubernetes-engines
  include_role:
    name: "{{ item }}"
    apply:
      tags:
        - cleanup
  with_items:
    - kube_02_install_k8s
    - kube_02_install_minikube
    - kube_02_install_rke
  tags: [ nocleanup ]
    

- name: Download k3s
  include_tasks: k3s-download.yml
  when: 
    - serveNet_ip is defined
    - kubernetes_engine == "k3s"
  tags: [ download ]

- name: Create k3s-users
  include_tasks: k3s-create_user.yml
  when: 
    - k8s_node in [ "install_master", "become_master", "node" ]
    - serveNet_ip is defined
    - kubernetes_engine == "k3s"

- name: Setup k3s-master
  include_tasks: k3s-master.yml
  when: 
    - k8s_node == "install_master"
    - kubernetes_engine == "k3s"

- name: Setup k3s-node
  include_tasks: k3s-node.yml
  when: 
    - k8s_node in [ "become_master", "node" ]
    - kubernetes_engine == "k3s"
